# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSmoke():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_landingpage(self):
    self.driver.get("https://new.axilthemes.com/demo/template/etrade/index-1.html")
    self.driver.set_window_size(1536, 864)
    self.driver.find_element(By.CSS_SELECTOR, "#slick-slide60 > img").click()
    self.driver.find_element(By.CSS_SELECTOR, ".axil-main-slider-area .row").click()
    self.driver.find_element(By.ID, "slick-slide-control61").click()
    element = self.driver.find_element(By.ID, "slick-slide-control61")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.ID, "slick-slide-control62").click()
    self.driver.find_element(By.ID, "slick-slide-control63").click()
    self.driver.find_element(By.LINK_TEXT, "Check it Out!").click()
    self.driver.find_element(By.LINK_TEXT, "Add to Cart").click()
    self.driver.execute_script("window.scrollTo(0,2)")
  
  def test_accountandloginpage(self):
    self.driver.get("https://new.axilthemes.com/demo/template/etrade/index-1.html")
    self.driver.find_element(By.CSS_SELECTOR, ".flaticon-person").click()
    element = self.driver.find_element(By.LINK_TEXT, "Login")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.LINK_TEXT, "REGISTER HERE.").click()
    self.driver.find_element(By.NAME, "username").click()
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-bg-primary").click()
    self.driver.find_element(By.LINK_TEXT, "Sign In").click()
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-bg-primary").click()
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.LINK_TEXT, "Forget password?").click()
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-bg-primary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-bg-primary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-bg-primary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".back-btn").click()
    self.driver.find_element(By.CSS_SELECTOR, "img").click()
  
  def test_cart(self):
    self.driver.get("https://new.axilthemes.com/demo/template/etrade/index-1.html")
    self.driver.set_window_size(1536, 864)
    element = self.driver.find_element(By.LINK_TEXT, "Shop")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.LINK_TEXT, "Add to Cart").click()
    self.driver.find_element(By.LINK_TEXT, "Add to Cart").click()
    self.driver.find_element(By.CSS_SELECTOR, ".cart-count").click()
    self.driver.find_element(By.CSS_SELECTOR, ".cart-item:nth-child(3) .inc").click()
    self.driver.find_element(By.CSS_SELECTOR, ".cart-item:nth-child(3) .inc").click()
    element = self.driver.find_element(By.LINK_TEXT, "Checkout")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.LINK_TEXT, "Checkout").click()
  
  def test_checkout(self):
    self.driver.get("https://new.axilthemes.com/demo/template/etrade/index-1.html")
    self.driver.set_window_size(1536, 864)
    self.driver.find_element(By.ID, "slick-slide-control61").click()
    self.driver.find_element(By.ID, "slick-slide-control62").click()
    self.driver.find_element(By.CSS_SELECTOR, ".slick-dots").click()
    self.driver.find_element(By.ID, "slick-slide-control62").click()
    self.driver.find_element(By.ID, "slick-slide-control63").click()
    self.driver.find_element(By.LINK_TEXT, "Add to Cart").click()
    self.driver.find_element(By.CSS_SELECTOR, ".product-size-variation li:nth-child(2)").click()
    self.driver.find_element(By.LINK_TEXT, "Add to Cart").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) .inc").click()
    self.driver.find_element(By.LINK_TEXT, "Process to Checkout").click()
    self.driver.find_element(By.CSS_SELECTOR, ".single-payment:nth-child(2) label").click()
    self.driver.find_element(By.CSS_SELECTOR, ".axil-btn:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".input-group:nth-child(3) > label").click()
    self.driver.find_element(By.CSS_SELECTOR, ".axil-btn:nth-child(4)").click()
  
  def test_myprofle(self):
    self.driver.get("https://new.axilthemes.com/demo/template/etrade/index-1.html")
    self.driver.set_window_size(1536, 864)
    self.driver.find_element(By.CSS_SELECTOR, ".flaticon-person").click()
    self.driver.find_element(By.LINK_TEXT, "My Account").click()
    self.driver.find_element(By.LINK_TEXT, "Orders").click()
    element = self.driver.find_element(By.LINK_TEXT, "Downloads")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.LINK_TEXT, "Downloads").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.LINK_TEXT, "Addresses").click()
    self.driver.find_element(By.LINK_TEXT, "Account Details").click()
    self.driver.find_element(By.LINK_TEXT, "Dashboard").click()
    self.driver.find_element(By.LINK_TEXT, "Orders").click()
    self.driver.find_element(By.LINK_TEXT, "Addresses").click()
    self.driver.find_element(By.LINK_TEXT, "Account Details").click()
    self.driver.find_element(By.LINK_TEXT, "Addresses").click()
    self.driver.find_element(By.LINK_TEXT, "Downloads").click()
    self.driver.find_element(By.LINK_TEXT, "Orders").click()
    self.driver.find_element(By.LINK_TEXT, "View").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(3) .axil-btn").click()
    self.driver.find_element(By.LINK_TEXT, "Dashboard").click()
    self.driver.find_element(By.LINK_TEXT, "Log Out").click()
  
